server:
  port: 80
  servlet:
    #指定项目路径
    context-path: /consumer

spring:
  application:
    name: cloud-consumer-order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka