server:
  port: 7778
  servlet:
    #指定项目路径
    context-path: /testDemo

spring:
  application:
    name: test-service #微服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  redis:
    # redis数据库索引(默认为0)，我们使用索引2的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址
    host: localhost
    # redis访问密码（默认为空）
    password:
    # redis端口（默认为6379）
    port: 6379
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 100
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 20
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 10
        #从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 10000
    timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#  zipkin: #微服务调用链路
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1

  datasource: #数据库连接信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?characterEncoding=utf8&useUnicode=true
    username: root
    password: 12345678

mybatis: #mybatis扫描
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springclous.entities

#eureka:
#  client: #注册微服务
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true
