server:
  port: 3344

#配置中心
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PengYD/cloudConfig.git
          search-paths:
            - cloudConfig
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
