server:
  port: 80
  servlet:
    #指定项目路径
    context-path: /consumer

spring:
  application:
    name: cloud-consumer-order

#feign超时等待
#建立连接等待时间
#返回等待时间(默认1秒钟)
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

#feign日志
logging:
  level:
    #监控接口和级别
    com.atguigu.springcloud.service.PaymentFeignServiceImp: debug

feign:
  hystrix:
    enabled: true

#这里只把feign做客户端用，不注册进eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka

