server:
  port: 3344

# http://localhost:3344/config-dev.yml

# 刷新配置 POST请求
# http://localhost:3344/actuator/bus-refresh

# 刷新具体某个节点
# http://localhost:3344/actuator/bus-refresh/config-client:3355

#配置中心
spring:
  application:
    #注册进Eureka服务器的微服务名
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PengYD/cloudConfig.git
          ####搜索目录
          search-paths:
            - cloudConfig
      ####读取分支
      label: master

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#服务注册到eureka地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
