server:
  port: 80
  servlet:
    #指定项目路径
    context-path: /consumer

spring:
  application:
    name: cloud-consumer-order


#feign超时等待
  #建立连接等待时间
  #返回等待时间(默认1秒钟)
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: consumer-feign
    prefer-ip-address: true
