server:
  port: 80
  servlet:
    #指定项目路径
    context-path: /consumer

spring:
  application:
    name: cloud-consumer-order
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: Order80
    prefer-ip-address: true
